ruby '2.6.3'
source "https://rubygems.org"

gem "fastlane", "2.162.0"
gem 'RegExpr', '0.0.2'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

