platform :ios, '9.0'
inhibit_all_warnings!


target 'mutea' do
	use_frameworks!

	pod 'CocoaLumberjack', '~> 3.2.0'
	pod 'RxSwift', '~> 3.6.0'
end

target 'muteaTests' do
	use_frameworks!

	pod 'Quick', '~> 1.1.0'
	pod 'Nimble', '~> 7.0.1'
end
